baseURL = "https://konglong87.github.io"
author = "KongLong"
copyright = "Copyright © 2008–2099, KongLong and the sy; all rights reserved."
paginate = 3
languageCode = "zh"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "hugo-paper"
title = "🦖"

[params]
  color = 'light'   # linen, wheat, gray, light

  twitter = 'konglong'
  github = 'konglong'
  instagram = 'konglong'

 #avatar = 'https://img1.baidu.com/it/u=1682993514,2737209100&fm=253&fmt=auto&app=138&f=JPEG?w=902&h=500'
  avatar = 'https://konglong87.github.io/avatar1.png'
  name = 'konglong🦖'
  bio = 'KL ❤️ SY'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = false
    simple = true

  [privacy.instagram]
    disabled = false
    simple = false

  [privacy.youtube]
    disabled = false
    privacyEnhanced = false

[services]

  [services.instagram]
    disableInlineCSS = false

  [services.twitter]
    disableInlineCSS = false
